cc_library(
    name = "transformer",
    srcs = ["transformer.cc"],
    deps = [
        "//include/vvllm/model:transformer",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "model",
    srcs = ["model.cc"],
    deps = [
        "//include/vvllm/model",
        "//src/model/llama",
        "//src/model/qwen2",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "model_bench",
    srcs = ["model_bench.cc"],
    deps = [
        ":transformer",
        "//include/vvllm/model:transformer",
        "//include/vvllm/model/llama",
        "//src/backend",
        "//src/backend:backend_blas",
        "//src/quantize",
        "@google_benchmark//:benchmark_main",
    ],
)
