cc_library(
    name = "tensor",
    srcs = ["tensor.cc"],
    deps = [
        "//include/vvllm/tensor",
        "//src/backend:cuda_kernels",
        "//third_party/cuda:cublas",
        "//third_party/cuda:cuda_runtime",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "tensor_test",
    srcs = ["tensor_test.cc"],
    deps = [
        ":tensor",
        "@googletest//:gtest_main",
    ],
)
